# NumPy 存储数据到文件

In [2]:
import numpy as np

In [4]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 存

In [5]:
np.save('array_1', a)

In [6]:
!ls

array_1.npy  Numpy_array.ipynb	Numpy_IO.ipynb


## 取

In [11]:
b = np.load('array_1.npy')
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 压缩存储

In [12]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.savez('array_z', a, b)

In [15]:
!ls

array_1.npy  array_z.npz  Numpy_array.ipynb  Numpy_IO.ipynb


In [16]:
arrays = np.load('array_z.npz')

In [18]:
arrays

In [19]:
arrays.files

['arr_0', 'arr_1']

In [20]:
arrays['arr_0']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arrays['arr_1']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 文本文件的存储


In [22]:
a = np.arange(10) 
np.savetxt('array.txt',a) 

In [23]:
!ls

array_1.npy  array.txt	array_z.npz  Numpy_array.ipynb	Numpy_IO.ipynb


In [26]:
b = np.loadtxt('array.txt')
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 保存为 csv 文件

In [27]:
a = np.ones((5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.savetxt('array.csv', a, fmt='%d', delimiter=',')

In [29]:
!ls

array_1.npy  array.txt	  Numpy_array.ipynb
array.csv    array_z.npz  Numpy_IO.ipynb


In [35]:
a = np.loadtxt('array.csv', delimiter=',')
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])